version: "3.7"
volumes:
  db-data:
networks:
  backend:
  frontend:
services:
  app-server:
    build:
      context: ./polling-app-server
      dockerfile: Dockerfile
    ports: ["8080:8080"]
    restart: always
    depends_on: [db]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polls?allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: callicoder
      SPRING_DATASOURCE_PASSWORD: callicoder
    networks:
    - backend
    - frontend
  app-client:
    build:
      context: ./polling-app-client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports: ["9090:80"]
    restart: always
    depends_on: [app-server]
    networks: [frontend]
  db:
    image: library/mysql:8.0.19
    ports: ["3306:3306"]
    restart: always
    environment:
      MYSQL_DATABASE: polls
      MYSQL_USER: callicoder
      MYSQL_PASSWORD: callicoder
      MYSQL_ROOT_PASSWORD: root
    volumes: [db-data:/var/lib/mysql]
    networks: [backend]
